#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# export TERM='kitty'
export TERM='xterm-ghostty'

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# PATH
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/bin-sh/global/"
export PATH="$PATH:$HOME/.dotnet/tools"
export PATH="$PATH:$HOME/.npm-global"

# X11
# export XINITRC="$XDG_CONFIG_HOME/X11/.xinitrc"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# prompt
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"

# rust
export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"

# Man pages
export MANPAGER='nvim +Man!'

# NPM
export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

# Minecraft (Prism Launcher)
export MC_PRISM="$HOME/.var/app/org.prismlauncher.PrismLauncher"
export MC_PRISM_INST="$MC_PRISM/data/PrismLauncher/instances"
export MC_PRISM_1_21="$MC_PRISM_INST/1.21/.minecraft"
export MC_PRISM_LATEST="$MC_PRISM_1_21"

# fzf

export FZF_DEFAULT_COMMAND="git ls-files --cached --others --exclude-standard || fd --type f"
# Open in tmux popup (centered) if on tmux, otherwise use --height mode
# Set color theme to Catppuccin Mocha theme
export FZF_DEFAULT_OPTS=" \
    --style=full --layout reverse --border --padding 1,2 --height 80% --tmux 80% \
    --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
    --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
    --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
    --bind 'ctrl-/:toggle-preview'"

# zoxide
export _ZO_EXCLUDE_DIRS="$HOME/Documents/private/*"
TREE_CMD="eza --color=always --icons --group-directories-first --tree --level=3"
export _ZO_FZF_OPTS="$FZF_DEFAULT_OPTS \
    --border-label ' Zoxide Interactive ' --input-label ' Input ' \
    --list-label ' Jump List ' --preview-label ' Directory Structure ' \
    --bind 'ctrl-/:toggle-preview' \
    --preview=\"echo {} | awk '{print \$2}' | xargs $TREE_CMD\""

# Personal
export SCRIPTS="$XDG_CONFIG_HOME/scripts"
export WALLPAPERS_DIR="$HOME/Pictures/Wallpapers"
export WORKSPACE="$HOME/Workspace"

# ⚠️ Make sure those env vars are set here properly BEFORE we set _ZO_EXCLUDE_DIRS
# If theses variables are unset, this might result in clearing the entire Z database
export PROJ_WORK="$WORKSPACE/work"
export PROJ_PERSO="$WORKSPACE/personal"

# opencode
export PATH=/home/coco/.opencode/bin:$PATH
